post_install() {
  systemd-sysusers artifactory-oss.conf
  systemd-tmpfiles --create artifactory-oss.conf
  chown -R artifactory:artifactory /etc/webapps/artifactory-oss /usr/share/webapps/artifactory-oss

  echo
  echo 'For the Artifactory user guide and installation instructions please visit:'
  echo
  echo '  http://wiki.jfrog.org/confluence/display/JFROG'
  echo
  echo 'The default administrator user is:'
  echo '  username: admin'
  echo '  password: password'
  echo
  echo 'The default port is 8082'
  echo
  echo 'Please configure an external database: https://www.jfrog.com/confluence/display/JFROG/Configuring+the+Database'
  echo
}

post_upgrade() {
  getent passwd artifactory >/dev/null 2>&1 || systemd-sysusers artifactory-oss.conf
  systemd-tmpfiles --create artifactory-oss.conf
  chown -R artifactory:artifactory /etc/webapps/artifactory-oss /usr/share/webapps/artifactory-oss

  echo "Removing tomcat work directory"
  if [ -d /usr/share/webapps/artifactory-oss/app/artifactory/tomcat/work ]
  then
    rm -rf /usr/share/webapps/artifactory-oss/app/artifactory/tomcat/work
  fi

  if [ -d /usr/share/webapps/artifactory-oss/app/artifactory/tomcat/webapps/artifactory ]
  then
    echo "Removing Artifactory's exploded WAR directory"
    rm -rf /usr/share/webapps/artifactory-oss/app/artifactory/tomcat/webapps/artifactory
  fi

  if [ -f /var/run/artifactory-oss/artifactory.pid ]
  then
    echo "Removing Artifactory's PID file"
    rm -f /var/run/artifactory-oss/artifactory.pid
  fi
}
